// <auto-generated />
using BonelessPharmacyBackend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace BonelessPharmacyBackend.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20170904003449_SalesItems Table")]
    partial class SalesItemsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("BonelessPharmacyBackend.SalesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.Property<uint>("StockOnHand");

                    b.Property<string>("SupplierCode");

                    b.HasKey("Id");

                    b.ToTable("SalesItems");
                });
#pragma warning restore 612, 618
        }
    }
}
