// <auto-generated />
using BonelessPharmacyBackend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace BonelessPharmacyBackend.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20170904013016_Fresh Migration, SalesItem and Measurements")]
    partial class FreshMigrationSalesItemandMeasurements
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("BonelessPharmacyBackend.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Suffix")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("BonelessPharmacyBackend.SalesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Amount");

                    b.Property<int>("MeasurementId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.Property<uint>("StockOnHand");

                    b.Property<string>("SupplierCode");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId");

                    b.ToTable("SalesItems");
                });

            modelBuilder.Entity("BonelessPharmacyBackend.SalesItem", b =>
                {
                    b.HasOne("BonelessPharmacyBackend.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
